# Internal
# =======
archetypeDir: private/archtypes
assetsDir: assets
contentDir: private/content
dataDir: private/data
layoutDir: templates
publishDir: dist
staticDir: static 

# Entries
# =======
metaDataFormat: yaml

defaultContentLanguage: ja
defaultLanguageCode: ja
hasCJKLanguage: true
languageCode: ja

# URL
# ===
disablePathToLower: true

permalinks:
  archives: /:filename/
  echos: /echos/:year/:month/:day/:filename/
  home: /:filename/
  notes: /notes/:slug/
  posts: /posts/:year/:month/:day/:filename/

paginate: 15
paginatePath: pages

# Output
# =======
disableHugoGeneratorInject: true
disableKinds:
  - taxonomy
  - term

enableRobotsTXT: true

imaging:
  quality: 100

mediaTypes:
  application/x-yaml:
    suffixes:
      - yaml
  application/atom+xml:
    suffixes:
      - xml

outputFormats:
  JSONFeed:
    mediaType: application/json
    baseName: jsonfeed
    isPlainText: true
  Atom:
    mediaType: application/atom+xml
    baseName: atom
    isPainText: false
  Test:
    mediaType: application/x-yaml
    baseName: test
    isPlainText: true
  Fixture:
    mediaType: application/x-yaml
    baseName: fixture
    isPlainText: true

outputs:
  home:
    - HTML
    - Atom
    - RSS
    - JSONFeed
  section:
    - HTML
    - Atom
    - RSS
    - JSONFeed
    - Test
  page:
    - HTML
    - Test
    - Fixture

# Content
# =======
summaryLength: 140

markup:
  goldmark:
    extensions:
      definitionList: false
      footnote: false
      linkify: false
      strikethrough: true
      table: true
      taskList: false
      typographer: false
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: false
    tabWidth: 2

pygmentsUseClasses: true

# Varialbes
# =========

title: カラクリスタ

params:
  menus:
    posts:
      name: ブログ
      aria: "ブログ記事の一覧へ"
    echos:
      name: 日記
      aria: "日記記事の一覧へ"
    notes:
      name: ノート
      aria: "ノート記事一覧へ"
    nyarla:
      name: 筆者
      aria: "このウェブサイトを運営者について"
    policies:
      name: 運営方針
      aria: "このウェブサイトの基本的な方針について"
    licenses:
      name: 権利情報
      aria: "利用しているライブラリやコンテンツのライセンスについて"
    search:
      name: 検索
      aria: "Google Custom Search による全文検索"
      url: 'https://cse.google.com/cse?cx=018101178788962105892:toz3mvb2bhr#gsc.tab=0'

  schemaorg:
    index:
      home: WebSite
      tags: WebSite
      posts: Blog
      echos: Blog
      notes: WebSite
      columns: Blog
    page:
      home: WebPage
      posts: BlogPosting
      echos: BlogPosting
      notes: Article
      columns: Article
      search: WebPage
      archives: WebPage

  titles:
    posts: カラクリスタ・ブログ
    echos: カラクリスタ・エコーズ
    notes: カラクリスタ・ノート

  descriptions:
    home: "『輝かしい青春』なんて失かった方の『[にゃるら](https://the.kalaclista.com/nyarla/)』の Webサイトです。"
    posts: "『輝かしい青春』なんて失かった方の『[にゃるら](https://the.kalaclista.com/nyarla/)』のブログです。"
    echos: "『輝かしい青春』なんて失かった方の『[にゃるら](https://the.kalaclista.com/nyarla/)』の日記です。"
    notes: "『輝かしい青春』なんて失かった方の『[にゃるら](https://the.kalaclista.com/nyarla/)』の Wiki っぽいヤツです。"

  cards:
    item:
      order:
        - amazon
        - rakuten
        - aliexpress
        - banggood
        - gearbest
      labels:
        amazon: 'Amazon.co.jp で買う'
        rakuten: '楽天で探す'
        aliexpress: 'Aliexpress から輸入する'
        banggood: 'Banggood で輸入する'
        gearbest: 'Gearbest で輸入する'
