# Internal
# =======
archetypeDir: archetypes
assetsDir: assets
contentDir: private/content
dataDir: private/data
layoutDir: templates
publishDir: dist
staticDir: static 

# Entries
# =======
metaDataFormat: yaml

defaultContentLanguage: en
defaultLanguageCode: en
hasCJKLanguage: true
languageCode: en

# URL
# ===
disablePathToLower: true

permalinks:
  archives: /:filename/
  echos: /echos/:year/:month/:day/:filename/
  home: /:filename/
  notes: /notes/:slug/
  posts: /posts/:year/:month/:day/:filename/

paginate: 15
paginatePath: pages

# Output
# =======
disableHugoGeneratorInject: true
disableKinds:
  - taxonomy
  - term

enableRobotsTXT: true

imaging:
  quality: 100

mediaTypes:
  application/x-yaml:
    suffixes:
      - yaml
  application/atom+xml:
    suffixes:
      - xml

outputFormats:
  JSONFeed:
    mediaType: application/json
    baseName: jsonfeed
    isPlainText: true
  Atom:
    mediaType: application/atom+xml
    baseName: atom
    isPainText: false
  Test:
    mediaType: application/x-yaml
    baseName: test
    isPlainText: true
  Fixture:
    mediaType: application/x-yaml
    baseName: fixture
    isPlainText: true

outputs:
  home:
    - HTML
    - Atom
    - RSS
    - JSONFeed
  section:
    - HTML
    - Atom
    - RSS
    - JSONFeed
    - Test
  page:
    - HTML
    - Test
    - Fixture

# Content
# =======
summaryLength: 140

markup:
  goldmark:
    extensions:
      definitionList: false
      footnote: false
      linkify: false
      strikethrough: true
      table: true
      taskList: false
      typographer: false
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: false
    tabWidth: 2

pygmentsUseClasses: true

# Varialbes
# =========

title: カラクリスタ

params:
  menus:
    posts:
      name: ブログ
    echos:
      name: 日記
    notes:
      name: メモ帳
    nyarla:
      name: 筆者
    policies:
      name: 運営方針
    licenses:
      name: 権利情報
    search:
      name: 検索
      url: 'https://cse.google.com/cse?cx=018101178788962105892:toz3mvb2bhr#gsc.tab=0'

  jsonld:
    types:
      home:
        - WebSite
        - WebPage
      posts:
        - Blog
        - BlogPosting
      echos:
        - Blog
        - BlogPosting
      notes:
        - WebSite
        - Article
    data:
      base:
        '@context': https://schema.org
        '@type': ''
        '@id': ''
        'headline': ''
        image:
          '@type': 'URL'
          url: https://the.kalaclista.com/assets/avatar.png
        author:
          '@type': Person
          name: OKAMURA Naoki aka nyarla
          email: 'nyarla@kalaclista.com'
        publisher:
          '@type': Organization
          name: the.kalaclista.com
          logo:
            '@type': ImageObject
            url:
              '@type': 'URL'
              url: https://the.kalaclista.com/assets/avatar.png
    root:
      home:
        '@id': https://the.kalaclista.com/
      posts:
        '@id': https://the.kalaclista.com/posts/
      echos:
        '@id': https://the.kalaclista.com/echos/
      notes:
        '@id': https://the.kalaclista.com/notes/
    items:
      home:
        '@type': ListItem
        position: 1
        name: カラクリスタ
        item: https://the.kalaclista.com/
      posts:
        '@type': ListItem
        position: 2
        name: カラクリスタ・ブログ
        item: https://the.kalaclista.com/posts/
      echos:
        '@type': ListItem
        position: 2
        name: カラクリスタ・エコーズ
        item: https://the.kalaclista.com/echos/
      notes:
        '@type': ListItem
        position: 2
        name: カラクリスタ・ノート
        item: https://the.kalaclista.com/notes/
    breadcrumb:
      '@context': https://schema.org
      '@type': BreadcrumbList

  schemaorg:
    index:
      home: WebSite
      tags: WebSite
      posts: Blog
      echos: Blog
      notes: WebSite
      columns: Blog
    page:
      home: WebPage
      posts: BlogPosting
      echos: BlogPosting
      notes: Article
      columns: Article
      search: WebPage
      archives: WebPage

  titles:
    posts: カラクリスタ・ブログ
    echos: カラクリスタ・エコーズ
    notes: カラクリスタ・ノート

  descriptions:
    home: "『輝かしい青春』なんて失かった方の『[にゃるら](https://the.kalaclista.com/nyarla/)』の Webサイトです。"
    posts: "『輝かしい青春』なんて失かった方の『[にゃるら](https://the.kalaclista.com/nyarla/)』のブログです。"
    echos: "『輝かしい青春』なんて失かった方の『[にゃるら](https://the.kalaclista.com/nyarla/)』の日記です。"
    notes: "『輝かしい青春』なんて失かった方の『[にゃるら](https://the.kalaclista.com/nyarla/)』の Wiki っぽいヤツです。"

  cards:
    affiliate:
      labels:
        aliexpress: 'Aliexpress から輸入する'
        amazon: 'Amazon.co.jp で買う'
        banggood: 'Banggood で輸入する'
        gearbest: 'Gearbest で輸入する'
        rakuten: '楽天で探す'

  jsonfeed:
    author:
      name: OKAMURA Naoki aka nyarla
      url: https://the.kalaclista.com/nyarla/
      avatar: https://the.kalaclista.com/assets/avatar.png
